CarDealershipDatabase Example/CarDealership.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarDealership.Models;
using CarDealership.BLL;


namespace CarDealership.Web.Controllers
{
    public class AdminController : Controller
    {
        RequestManager requestOps = new RequestManager();
        

        
        // GET: Admin
        public ActionResult ListOfRequests()
        {
            var request = requestOps.GetListOfRequests();
            return View(request);
        }

        public ActionResult RequestDetail(int RequestID)
        {
            var request = requestOps.GetRequestById(RequestID);
            return View(request);

        }
        [HttpGet]
        public ActionResult AddRequest(int VehicleId)
        {

            var request= new Request();
            request.VehicleId = VehicleId;
      

            return View(request);
        }

        [HttpPost]
        public ActionResult AddRequest(Request request)
        {
            var ops = new RequestManager();
            ops.AddRequest(request);

            return RedirectToAction("ListOfRequests");


        }
        [HttpGet]
        public ActionResult EditRequest(int RequestID)
        {

            var ops = new RequestManager();
            var request=ops.GetRequestById(RequestID);
            return View(request);
        }

        [HttpPost]
        public ActionResult EditRequest(Request request)
        {
            var ops = new RequestManager();
            ops.EditResponse(request);

            return RedirectToAction("ListOfRequests");


        }
        [HttpGet]
        public ActionResult RemoveRequest(int RequestID)
        {

            var ops = new RequestManager();
            var request = ops.GetRequestById(RequestID);
            return View(request);
        }

        [HttpPost]
        public ActionResult RemoveRequest(Request request)
        {
            var ops = new RequestManager();
            ops.DeleteRequest(request.RequestID);

            return RedirectToAction("ListOfRequests");


        }
    }
}

CarDealershipDatabase Example/CarDealership.Web/Controllers/CarAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using CarDealership.BLL;
using CarDealership.Models;

namespace CarDealership.Web.Controllers
{
    public class CarAPIController : ApiController
    {
        public List<Vehicle> Get()
        {

            var ops = new OperationsManager();
            return ops.ListCars();
        }

        public Vehicle Get(int vehicleID)
        {
            var ops = new OperationsManager();
            return ops.GetVehicleById(vehicleID);
        }

        public HttpResponseMessage Post(Vehicle car)
        {
            var ops = new OperationsManager();
            ops.AddCarResponse(car);
            return new HttpResponseMessage(HttpStatusCode.OK);
        }

    }
}

CarDealershipDatabase Example/CarDealership.Web/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarDealership.BLL;
using CarDealership.Models;

namespace CarDealership.Web.Controllers
{
    public class CarController : Controller
    {
        OperationsManager ops = new OperationsManager();

        [HttpGet]
        public ActionResult CarDetail(int VehicleId)
        {

            var CarToView = ops.GetVehicleById(VehicleId);
            return View(CarToView);
        }

        [HttpGet]
        public ActionResult AddCar()
        {
            var vehicle = new Vehicle();
            return View(vehicle);
        }

        [HttpPost]
        public ActionResult AddCar(Vehicle car)
        {
            var response = ops.AddCarResponse(car);

            return RedirectToAction("Home");
        }


        [HttpGet]
        public ActionResult RemoveCar(int vehicleID)
        {
            var vehicle = ops.GetVehicleById(vehicleID);

            return View(vehicle);
        }

        [HttpPost]
        public ActionResult RemoveCar(Vehicle vehicle)
        {
            var response = ops.DeleteVehicle(vehicle.VehicleId);

            return RedirectToAction("Home");
        }


        [HttpGet]
        public ActionResult EditCar(int VehicleId)
        {
            
            var CarToEdit= ops.GetVehicleById(VehicleId);
            return View(CarToEdit);
        }

        [HttpPost]
        public ActionResult EditCar(Vehicle car)
        {  
            ops.EditVehicle(car);
            return RedirectToAction("Home");
        }
        public ActionResult RequestInfo()
        {
            return View();
        }

  

        public ActionResult Home()
        {
            return View();
        }

        public ActionResult CarPortal()
        {
            return View();
        }

        public ActionResult CarPortalCarDetails(int VehicleId)
        {
            var CarToView = ops.GetVehicleById(VehicleId);
            return View(CarToView);
        }
    }
}

CarDealershipDatabase Example/CarDealership.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Home()
        {
            return View();
        }
    }
}

CarDealershipDatabase Example/CarDealership.Web/Views/Admin/AddRequest.cshtml
@model CarDealership.Models.Request

@{
    ViewBag.Title = "AddRequest";
}

<h2>AddRequest</h2>

@using (Html.BeginForm("AddRequest", "Admin", null, FormMethod.Post, new {id ="requestForm"}))
{


    <form>
        @Html.HiddenFor(r =>r.VehicleId)
        
        <div class="form-group">
            <label>Customer Name: </label>
            @Html.TextBoxFor(r => r.CustomerName, new {@class = "form-control"})
        </div>
        <div class="form-group">
            <label>Phone: </label>
            @Html.TextBoxFor(r => r.Phone, new {@class = "form-control", placeholder = "Phone"})
        </div>
        <div class="form-group">
            <label>Best Time To Call: </label>
            @Html.EnumDropDownListFor(r => r.TimeToCall, "-Choose One-", new { @class = "form-control"})
        </div>
     
        <div class="form-group">
            <label>Email: </label>
            @Html.TextBoxFor(r => r.Email, new { @class = "form-control", placeholder = "Email" })
        </div>
        <div class="form-group">
            <label>Contact  Method: </label>
            @Html.TextBoxFor(r => r.ContactMethod, new {@class = "form-control"})
        </div>
 
        <div class="form-group">
            <label>Time Frame to Purchase</label>
            @Html.TextBoxFor(r => r.TimeFrame, new { @class = "form-control" })
        </div>
    

        <button type="submit" class="btn btn-success">Submit</button>

    </form>
}
@section scripts{

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/additional-methods.min.js"></script>
    <script src="~/Scripts/app/jQueryFormValidation.js"></script>
    <script src="~/Scripts/app/JSFormValidation.js"></script>

}  

CarDealershipDatabase Example/CarDealership.Web/Views/Admin/EditRequest.cshtml
@model CarDealership.Models.Request

@{
    ViewBag.Title = "EditRequest";
}

<h2>EditRequest</h2>

@using (Html.BeginForm())
{



    <form>
        @Html.HiddenFor(r =>r.RequestID)

        @Html.HiddenFor(r => r.VehicleId)
   
        <div class="form-group">
            <label>Customer Name </label>
            @Html.TextBoxFor(r => r.CustomerName, new {@class = "form-control", placeholder ="Name"})
        </div>
        <div class="form-group">
            <label>Phone: </label>
            @Html.TextBoxFor(r => r.Phone, new {@class = "form-control", placeholder = "Phone"})
        </div>
        <div class="form-group">

            <label>Best Time To Call</label>
            @Html.EnumDropDownListFor(r => r.TimeToCall, new {@class = "form-control"})

        </div>
        <div class="form-group">
            <label>Email: </label>
            @Html.TextBoxFor(r => r.Email, new {@class = "form-control", placeholder = "Email"})
        </div>
        <div class="form-group">
            <label>Contact Method: </label>
            @Html.TextBoxFor(r => r.ContactMethod, new {@class = "form-control", placeholder = "Contact Method"})
        </div>
        <div class="form-group">
            <label>Make:</label>
            @Html.TextBoxFor(r => r.VehicleName, new { @class = "form-control", placeholder = "Make" })
        </div>
        <div class="form-group">
            <label>Model:</label>
            @Html.TextBoxFor(r => r.VehicleName, new {@class = "form-control", placeholder = "Model"})
        </div>
        <div class="form-group">
            <label>Time Frame For Purchase: </label>
            @Html.TextBoxFor(r => r.TimeFrame, new { @class = "form-control", placeholder = "TimeFrame" })
        </div>
        <div class="form-group">
            <label>Status of Request: </label>
            @Html.EnumDropDownListFor(r => r.StatusOfRequest, new { @class = "form-control" })

        </div>
        
        



        <button type="submit" class="btn btn-success">Submit</button>

    </form>
}

CarDealershipDatabase Example/CarDealership.Web/Views/Admin/ListOfRequests.cshtml
@model List<CarDealership.Models.Request>
@{
    ViewBag.Title = "ListOfRequests";
}

<h2>Vehicle Requests</h2>


<div class="container">
    @foreach (var request in Model)
    {

        <div class="row" id="requestList">
            <div class="col-lg-6">
                <h4>
                    @Html.ActionLink($"{request.RequestID} - {request.CustomerName} - {request.VehicleName}",
                    "RequestDetail", "Admin", new { RequestID = request.RequestID }, null)
                </h4>
                @if(request.StatusOfRequest == CarDealership.Models.RequestStatus.New)
                {
                        <p class ="blink" id="newRequest">NEW REQUEST !!</p>  
                }


                <br/>
            </div>
        </div>
    }
    
</div>
@section scripts{
    <script src="~/scripts/app/BlinkFunction.js"></script>
    <script src="~/scripts/app/blink.js"></script>
}

CarDealershipDatabase Example/CarDealership.Web/Views/Admin/RemoveRequest.cshtml
@model CarDealership.Models.Request

@{
    ViewBag.Title = "RemoveRequest";
}

<h2>Remove Request</h2>


<div class="row">


    <div class="col-xs-12 col-sm-3">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(r=>r.RequestID)
            <p> Are you sure want to delete the request for: @Model.CustomerName - @Model.VehicleName?</p>
            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
            @Html.ActionLink("Cancel", "ListOfRequests", "Admin", null, new { @class = "btn btn-primary btn-sm" })

        }
    </div>
</div>

CarDealershipDatabase Example/CarDealership.Web/Views/Admin/RequestDetail.cshtml
@model CarDealership.Models.Request
@{
    ViewBag.Title = "RequestDetail";
}

<h2>Vehicle Information Requests</h2>

<div class="container">
    <div class="row">

     
        @Html.HiddenFor(m => m.RequestID)
    </div>
    <div class="row">
        <div class="col-sm-4">
            <h5>Customer Name: </h5>
        </div>
        <div class="col-sm-6">@Model.CustomerName</div>
    </div>

    <div class="row">
        <div class="col-sm-4">
            <h5>Phone: </h5>
        </div>
        <div class="col-sm-6">@Model.Phone</div>
    </div>

    <div class="row">
        <div class="col-sm-4">
            <h5>Best Time To Call: </h5>
        </div>
        <div class="col-sm-6">@Model.TimeToCall</div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <h5>Email:</h5>
        </div>
        <div class="col-sm-6">@Model.Email</div>
    </div>

    <div class="row">
        <div class="col-sm-4">
            <h5>Contact Method: </h5>
        </div>
        <div class="col-sm-6">@Model.ContactMethod</div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <h5>Vehicle Name: </h5>
        </div>
        <div class="col-sm-6">@Model.VehicleName</div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <h5>Time Frame: </h5>
        </div>
        <div class="col-sm-6">@Model.TimeFrame</div>
    </div>
    <div class="row">
        <div class="col-sm-4">

            <h5>Status of Request: </h5>
        </div>
        <div class="col-sm-6">@Model.StatusOfRequest</div>

    </div>

        @*<div class="row">
                <div class="col-sm-4">
                    <h5>Vehicle ID</h5>
                </div>
                <div class="col-sm-6">@Model.VehicleId</div>

            </div>
            <div class="row">
                <div class="col-sm-4">
                    <h5>Request ID</h5>
                </div>
                <div class="col-sm-6">@Model.RequestID</div>
            </div>*@



    </div>
@Html.ActionLink("Edit", "EditRequest", "Admin", new { RequestID = Model.RequestID },
                                 new { @class = "btn btn-primary" })
@Html.ActionLink("Delete", "RemoveRequest", "Admin", new { RequestID = Model.RequestID },
                                 new { @class = "btn btn-danger" })

CarDealershipDatabase Example/CarDealership.Web/Views/Car/AddCar.cshtml
@model CarDealership.Models.Vehicle
@{
    ViewBag.Title = "AddCar";
}

<h2>Add a Car</h2>


@using (Html.BeginForm("AddCar", "Car", null, FormMethod.Post, new { id = "carForm" }))
{

    @Html.ActionLink("List of Cars", "Home", "Car", new { VehicleId = Model.VehicleId },
                                 new { @class = "btn btn-primary" })

    <form>
        <div class="form-group">
            <label>Year </label>
            @Html.TextBoxFor(m => m.Year, new { @class = "form-control"})
        </div>
        <div class="form-group">
            <label>Make </label>
            @Html.TextBoxFor(m => m.Make, new { @class = "form-control", placeholder = "Make" })
        </div>
        <div class="form-group">
            <label>Model </label>
            @Html.TextBoxFor(m => m.Model, new { @class = "form-control", placeholder = "Model" })
        </div>
        <div class="form-group">
            <label>Mileage </label>
            @Html.TextBoxFor(m => m.Mileage, new { @class = "form-control"})
        </div>
        <div class="form-group">
            <label>Price </label>
            @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Description </label>
            @Html.TextBoxFor(m => m.Description, new { @class = "form-control", placeholder = "Description" })
        </div>
        <div class="form-group">
            <label>Ad Title</label>
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control", placeholder = "Title for Ad" })
        </div>
        <div class="form-group">
            <label>Current Status</label>
            @Html.EnumDropDownListFor(m => m.status, "-Choose One-", new { @class = "form-control"})
        </div>
        <button type="submit" class="btn btn-success">Submit</button>

    </form>
}
@section scripts{

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/additional-methods.min.js"></script>
    <script src="~/Scripts/app/jQueryFormValidation.js"></script>
    <script src="~/Scripts/app/JavaScriptAddCarValidation.js"></script>

}  

CarDealershipDatabase Example/CarDealership.Web/Views/Car/CarDetail.cshtml
@model CarDealership.Models.Vehicle
@{
    ViewBag.Title = "CarDetail";
}

    <h2>Vehicle Details</h2>
<h2>@Model.Year - @Model.Make, @Model.Model</h2>

<div class="container">
    <div class="row">

        @Html.HiddenFor(m => m.VehicleId)
    </div>

    <div class="row">
        <div class="col-sm-4"><h5>Year:</h5>
        </div>
        <div class="col-sm-6">@Model.Year</div>
    </div>

    <div class="row">
        <div class="col-sm-4"><h5>Vehicle Make:</h5>
        </div>
        <div class="col-sm-6">@Model.Make</div>
    </div>
    <div class="row">
        <div class="col-sm-4"><h5>Vehicle Model:</h5>
        </div>
        <div class="col-sm-6">@Model.Model</div>
    </div>

    <div class="row">
        <div class="col-sm-4"><h5>Mileage:</h5>
        </div>
        <div class="col-sm-6">@Model.Mileage</div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <h5>Price:</h5>
        </div>
        <div class="col-sm-6">@Model.Price</div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <h5>Vehicle Description:</h5>
        </div>
        <div class="col-sm-6">@Model.Description</div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <h5>Inventory Status:</h5>
        </div>
        <div class="col-sm-6">@Model.status</div>
    </div>
</div>

@Html.ActionLink("Edit", "EditCar", "Car", new { VehicleId = Model.VehicleId},
                                 new { @class = "btn btn-primary" })
@Html.ActionLink("Delete", "RemoveCar", "Car", new { VehicleId = Model.VehicleId },
                                 new { @class = "btn btn-danger" })

CarDealershipDatabase Example/CarDealership.Web/Views/Car/CarPortal.cshtml
@{
    ViewBag.Title = "CarPortal";
}

<h2>Cars In Stock</h2>




<div ng-app="carPortalApp" ng-view="">

</div>

@section scripts{
    <script src="~/Scripts/angular-route.min.js"></script>
    <script src="~/Scripts/app/routesclient.js"></script>
}

CarDealershipDatabase Example/CarDealership.Web/Views/Car/CarPortalCarDetails.cshtml
@model CarDealership.Models.Vehicle
@{
    ViewBag.Title = "CarPortalCarDetails";
}


<h2>Vehicle Details</h2>
<h2>@Model.Year - @Model.Make, @Model.Model</h2>

<div class="container">
    <div class="row">
        @Html.HiddenFor(m => m.VehicleId)
    </div>

    <div class="row">
        <div class="col-sm-4">
            <h5>Year:</h5>
        </div>
        <div class="col-sm-6">@Model.Year</div>
    </div>

    <div class="row">
        <div class="col-sm-4">
            <h5>Vehicle Make:</h5>
        </div>
        <div class="col-sm-6">@Model.Make</div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <h5>Vehicle Model:</h5>
        </div>
        <div class="col-sm-6">@Model.Model</div>
    </div>

    <div class="row">
        <div class="col-sm-4">
            <h5>Mileage:</h5>
        </div>
        <div class="col-sm-6">@Model.Mileage</div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <h5>Price:</h5>
        </div>
        <div class="col-sm-6">@Model.Price</div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <h5>Vehicle Description:</h5>
        </div>
        <div class="col-sm-6">@Model.Description</div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <h5>Inventory Status:</h5>
        </div>
        <div class="col-sm-6">@Model.status</div>
    </div>



@Html.ActionLink("Request Info", "AddRequest", "Admin", new { VehicleId = Model.VehicleId },
                                 new { @class = "btn btn-primary" })

CarDealershipDatabase Example/CarDealership.Web/Views/Car/EditCar.cshtml
@model CarDealership.Models.Vehicle
@{
    ViewBag.Title = "EditCar";
}

<h2>EditCar</h2>


@using (Html.BeginForm())
{
   
    @Html.ActionLink("List of Cars", "Home", "Car", new { VehicleId = Model.VehicleId },
                                 new { @class = "btn btn-primary" })

    <form>
        <div class="form-group">
            @Html.HiddenFor(m=>m.VehicleId)
            <label>Year </label>
            @Html.TextBoxFor(m => m.Year, new {@class = "form-control"})
        </div>
        <div class="form-group">
            <label>Make </label>
            @Html.TextBoxFor(m => m.Make, new { @class = "form-control", placeholder = "Make" })
        </div>
        <div class="form-group">
            <label>Model </label>
            @Html.TextBoxFor(m => m.Model, new { @class = "form-control", placeholder = "Model" })
        </div>
        <div class="form-group">
            <label>Mileage </label>
            @Html.TextBoxFor(m => m.Mileage, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Price </label>
            @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label>Description </label>
            @Html.TextBoxFor(m => m.Description, new { @class = "form-control", placeholder = "Description" })
        </div>
        <div class="form-group">
            <label>Ad Title</label>
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control", placeholder = "Title for Ad" })
        </div>
        <div class="form-group">
            <label>Current Status</label>
            @Html.EnumDropDownListFor(m => m.status, "-Choose One-", new { @class = "form-control" })
        </div>
        <button type="submit" class="btn btn-success">Submit</button>

    </form>
}

CarDealershipDatabase Example/CarDealership.Web/Views/Car/Home.cshtml
@{
    ViewBag.Title = "Home";
}
<h2>Admin Portal</h2>
<div ng-app="carApp" ng-view="">

</div>


@section scripts{
    <script src="~/Scripts/angular-route.min.js"></script>
    <script src="~/Scripts/app/routes.js"></script>
}

CarDealershipDatabase Example/CarDealership.Web/Views/Car/RemoveCar.cshtml
@model CarDealership.Models.Vehicle
@{
    ViewBag.Title = "RemoveCar";
}

<h2>RemoveCar</h2>
<div class="row">
    @Html.ActionLink("Home", "Home", "Car", new { VehicleId = Model.VehicleId },
                                 new { @class = "btn btn-primary" })
</div>

<div class="row">
   
  
    <div class="col-xs-12 col-sm-3">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(m => m.VehicleId)
            <p> Are you sure want to delete @Model.Year @Model.Make @Model.Model?</p>
            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
            @Html.ActionLink("Cancel", "Home", "Car", null, new {@class = "btn btn-primary btn-sm" })
           
        }
    </div>
</div>

CarDealershipDatabase Example/CarDealership.Web/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Home";
}

<h3>Welcome to Immutable Auto Sales</h3>
<p>At Immutable Auto Sales, we've had the largest selection of New and Used cars, trucks and SUV's in North East Ohio since 2016. Visit our showroom today,</p>
<p> we are located at 123 Main Street in downtown Cleveland.</p>
<p> See something you like? Fill out a vehicle information request, our dedicated sales team would be happy to contact you to provide additional</p>
<p> details about your vehicle of choice.</p>

CarDealershipDatabase Example/CarDealership.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    
    <link rel="shortcut icon" href="~/Content/Images/Thumbnail Auto.png"/>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Immutable Auto Sales</title>
    <link href="https://fonts.googleapis.com/css?family=Economica|Play|Volkhov" rel="stylesheet">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    

</head>
<br/>
<body>
    <img src="~/Content/Images/skitter_banner_2.png" class="banner-image" width="1050" height="325"/>
<div class="navbar navbar-inverse navbar-fixed-top" id="navigation">

    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Immutable Auto Sales", "Home", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    @Html.ActionLink("Admin Portal", "Home", "Car")
                </li>
                <li>
                    @Html.ActionLink("Available Vehicles", "CarPortal", "Car")
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Immutable Auto Sales</p>
    </footer>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/scripts/angular.min.js"></script>
<script src="~/scripts/angular-route.min.js"></script>
@RenderSection("scripts", false)
</body>
</html>